---
title: '"casestudy2'
author: "Daniel M. Turner"
date: "February 8, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#load and prep data
library(readxl)

cs2 <- read_excel("C:\\Users\\DMT\\Documents\\masters\\semester1\\dds402\\CaseStudy2_2_2_2_2\\CaseStudy2-data.xlsx")

cs2a = cs2

cs2a$Attrition[cs2a$Attrition== "Yes"]<- 1
cs2a$Attrition[cs2a$Attrition== "No"]<- 0
cs2a$Attrition <- as.numeric(cs2a$Attrition)

cs2a$BusinessTravel[cs2a$BusinessTravel== "Non-Travel"]<- 0
cs2a$BusinessTravel[cs2a$BusinessTravel== "Travel_Rarely"]<- 1
cs2a$BusinessTravel[cs2a$BusinessTravel== "Travel_Frequently"]<- 2
cs2a$BusinessTravel <- as.numeric(cs2a$BusinessTravel)

cs2a$MaritalStatus[cs2a$MaritalStatus== "Single"]<- 0
cs2a$MaritalStatus[cs2a$MaritalStatus== "Married"]<- 1
cs2a$MaritalStatus[cs2a$MaritalStatus== "Divorced"]<- -1
cs2a$MaritalStatus <- as.numeric(cs2a$MaritalStatus)

cs2a$OverTime[cs2a$OverTime== "Yes"]<- 1
cs2a$OverTime[cs2a$OverTime== "No"]<- 0
cs2a$OverTime <- as.numeric(cs2a$OverTime)

cs2a$Gender[cs2a$Gender== "Male"]<- 0
cs2a$Gender[cs2a$Gender== "Female"]<- 1
cs2a$Gender <- as.numeric(cs2a$Gender)


drops <- c("Department","EducationField","JobRole","Over18","StandardHours","EmployeeCount","EmployeeNumber")
cs2a <- cs2a[ , !(names(cs2a) %in% drops)]

```

```{r}
##test correlation,  quick dirty test. not meaningful
BaseCor = data.frame(cor(cs2a$Attrition, cs2a[1:length(cs2a)]))
BaseCor$Attrition<-NULL

##lists index of top values. first is data correlated to itself so removed
top <- order(-BaseCor) ##identify fields starting with positive correlation
bottom <- order(BaseCor)##identify fields starting with negative correlation
BaseCor[top]
BaseCor[bottom]

```

```{r}
##count by department and gender
depcount <- data.frame(cs2$Attrition,cs2$Department,cs2$Gender)
table(depcount)
##                  M       F
##hr 23.5%          16.2%   42.9%             <-----  HR WTF?
##rnd = 16.1%       18.3%   12.8%
##sales = 26%       26.6%   25.2%



```

```{r}
##linear regressions
model = lm(Attrition ~ Age,
            data = cs2a)
summary(model)## cor = - .159, r = .02535, p = 8.356e-10
model = lm(Attrition ~ BusinessTravel,
            data = cs2a)
summary(model)## cor = .127, r =.01613, p = 1.033e-06
model = lm(Attrition ~ DailyRate,
           data = cs2a)
summary(model)## cor = -.0567, r = .003209, p = .02986
model = lm(Attrition ~ DistanceFromHome,
           data = cs2a)
summary(model)## cor = .0779, r = .00607, p = .002793
model = lm(Attrition ~ Education,
           data = cs2a)
summary(model)## cor = -.0314, r = .000984, p = 0.2293
###.... maybe not usefull?


###highest attrition
model = lm(Attrition ~ OverTime,
           data = cs2a)
summary(model)## cor = 0.246118, r =  0.06057, p = 2.2e-16
plot(cs2a$OverTime,cs2a$Attrition, xlim =c(0, 1), ylim =c(0, 1), ylab ="attrition", 
      xlab ="overtime")
displaylm <-lm(Attrition ~OverTime, data = cs2a)
abline(displaylm, col ="red")
##second
model = lm(Attrition ~ BusinessTravel,
            data = cs2a)
plot(cs2a$BusinessTravel,cs2a$Attrition, xlim =c(0, 2), ylim =c(0, 1), ylab ="attrition", 
      xlab ="travel")
displaylm <-lm(Attrition ~BusinessTravel, data = cs2a)
abline(displaylm, col ="red")
##third
model = lm(Attrition ~ DistanceFromHome,
            data = cs2a)
plot(cs2a$DistanceFromHome,cs2a$Attrition, xlim =c(0, 30), ylim =c(0, 1), ylab ="attrition", 
      xlab ="distance")
displaylm <-lm(Attrition ~DistanceFromHome, data = cs2a)
abline(displaylm, col ="red")

```

