---
title: "Explore Categorical Variable for Travel Management"
author: "Pankaj Kumar"
date: "2/9/2019"
output: html_document
params: 
  path: 'Analysis/Data/CaseStudy2-data.xlsx'
  echo: FALSE
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plyr)
job_data=readxl::read_excel(params$path)
job_data=job_data[job_data$Over18=='Y',]
grouped_data=group_by(job_data, Gender, Attrition) %>%
  summarise(count=n()) %>%
  mutate(perc= count)
draw_graph <- function(job_data, aa) {
  quo_group  <- sym(aa)
  business_travel_grouped_data=dplyr::group_by(job_data, !!quo_group, Attrition) %>%
    dplyr::summarise(count=n())  
  ce =ddply(business_travel_grouped_data , "Attrition" , 
            transform, percentage_weight = count/sum(count))
  graph <- ggplot(ce, aes(x=Attrition, y=percentage_weight, fill= !!quo_group))+
    geom_bar(stat="identity")
  geom_text((aes(label=percentage_weight)))
  graph
}

```


# check impact of different categorical variables  

```{r echo = params$echo}
draw_graph(job_data,"Education")
draw_graph(job_data,"EducationField")
draw_graph(job_data,"EnvironmentSatisfaction")
draw_graph(job_data,"Gender")
draw_graph(job_data,"JobInvolvement")
draw_graph(job_data,"JobLevel")
draw_graph(job_data,"JobRole")
draw_graph(job_data,"JobSatisfaction")
draw_graph(job_data,"MaritalStatus")
draw_graph(job_data,"MonthlyRate")
draw_graph(job_data,"NumCompaniesWorked")
draw_graph(job_data,"OverTime")
draw_graph(job_data,"PerformanceRating")
draw_graph(job_data,"RelationshipSatisfaction")
draw_graph(job_data,"StandardHours")
draw_graph(job_data,"StockOptionLevel")
draw_graph(job_data,"TotalWorkingYears")
draw_graph(job_data,"TrainingTimesLastYear")
draw_graph(job_data,"WorkLifeBalance")
draw_graph(job_data,"YearsAtCompany")
draw_graph(job_data,"YearsInCurrentRole")
draw_graph(job_data,"YearsSinceLastPromotion")
draw_graph(job_data,"YearsWithCurrManager")

```
 