---
title: "Explore Data For Travel Management"
author: "Pankaj Kumar"
date: "2/9/2019"
output: html_document
params: 
  path: 'Analysis/Data/CaseStudy2-data.xlsx'
  echo: FALSE
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
job_data=readxl::read_excel(params$path)
job_data=job_data[job_data$Over18=='Y',]


ggplot(data=job_data , aes(x=Attrition) )+
  geom_bar( mapping=aes( fill= BusinessTravel)) +
  geom_text(stat='count',aes(label=..count..), position = position_stack(vjust=.5), vjust=-1)
head(job_data)


p = ggplot(data=job_data , aes(x=Attrition) )

ggplot(data=job_data)+
  geom_bar(mapping=aes(x= JobInvolvement, y= MonthlyIncome , fill= Gender), 
           stat="identity")

ggplot(data=job_data)+
  geom_bar(mapping=aes(x= JobRole, y= MonthlyIncome , fill= Gender), 
           stat="identity")+
  theme(axis.text.x = element_text(angle = 90) )


ggplot(data=job_data)+
  geom_bar(mapping=aes(x= MaritalStatus, y= MonthlyIncome , fill= Gender), 
           stat="identity")+
  theme(axis.text.x = element_text(angle = 90) )



names(job_data)

p+geom_bar(mapping=aes(  fill=Gender), stat = "count")

attrition_data= job_data[job_data$Attrition=="Yes",]
non_attrition_data= job_data[job_data$Attrition=="No",]

ggplot(data=attrition_data)+
  geom_bar(mapping=aes(x= JobInvolvement , fill= Gender), 
           stat="count")+
  theme(axis.text.x = element_text(angle = 90) )


ggplot(data=non_attrition_data)+
  geom_bar(mapping=aes(x= JobInvolvement , fill= Gender), 
           stat="count")+
  theme(axis.text.x = element_text(angle = 90) )

p+geom_bar()
```
